Contradiction between ./cmake/Target.cmake (make doc command) and ./CMakeLists.txt (if condition).
Error when executing "make doc" command with DEO_ONLY=true flag :

Built target doc-eo
make[4]: *** No rule to make target `doc-edo'.  Stop.
make[3]: *** [CMakeFiles/doc] Error 2
make[2]: *** [CMakeFiles/doc.dir/all] Error 2
make[1]: *** [CMakeFiles/doc.dir/rule] Error 2
make: *** [doc] Error 2

Now resolved.

Contradiction between ./cmake/Target.cmake (make doc command) and ./CMakeLists.txt (if condition).

Error when executing "make doc" command with -DEO_ONLY=false flag :

make[4]: *** No rule to make target `doc-edo'.  Stop.
make[3]: *** [CMakeFiles/doc] Error 2
make[2]: *** [CMakeFiles/doc.dir/all] Error 2
make[1]: *** [CMakeFiles/doc.dir/rule] Error 2
make: *** [doc] Error 2

Now resolved.

Error and problems with smp documentation compilation ("make doc" or "make doc-smp" command with -DSMP=true flag).

Here the error :

error: Tag file `/home/aharrissart/workspace/thales/paradiseo/build/doc/smp.doxytag' does not exist or is not a file. Skipping it...

Some other problems with undocumented parameters...

Now resolved.

Comment unused EDO flag (declared in ../CMakeLists.txt file)